# Site settings
title: Alex Flannel
tag_text: Alex Flannel
description: Alex Flannel is a NY-based composer and producer.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
